#!/bin/bash

# Creates and signs a tarball and an .oxt


cd "$(dirname "$0")" || exit 1
cd ..

VERSION=$(grep --max-count 1 'version' meson.build | cut --delimiter=\' -f 2)
TARBALL=parlatype-libreoffice-extension-"$VERSION".tar.gz
OXT=Parlatype.oxt


if [ -e "$TARBALL" ]
then
	echo "$TARBALL exists – quitting now."
	exit 1
fi

if [ -e archive/v"$VERSION" ]
then
	echo "Archive for v$VERSION exists – quitting now."
	exit 1
fi

cd "$(dirname "$0")" || exit 1
source cd_builddir_or_exit

if [ -e $OXT ]
then
	echo "$OXT exists – quitting now."
	exit 1
fi

cd ..
mkdir archive/v"$VERSION"

git archive --format=tar --prefix=parlatype-libreoffice-extension-"$VERSION"/ main | gzip > "$TARBALL"
gpg --armor --detach-sign "$TARBALL"
mv "$TARBALL"* archive/v"$VERSION"

cd "$(dirname "$0")" || exit 1
source cd_builddir_or_exit

meson configure -Dbundled=false
ninja
gpg --armor --detach-sign "$OXT"
mv "$OXT"* ../archive/v"$VERSION"

cd ..
echo archive/v"$VERSION":
ls -l archive/v"$VERSION"
